"""Initial database setup with User and Prediction models

Revision ID: efc5f615bbce
Revises: 
Create Date: 2025-06-07 08:49:56.187576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc5f615bbce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('telecom_company', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('contract_duration', sa.String(length=50), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('monthly_charges', sa.Float(), nullable=True),
    sa.Column('data_usage_gb', sa.Float(), nullable=True),
    sa.Column('call_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('complaints_filed', sa.Integer(), nullable=True),
    sa.Column('customer_support_calls', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('internet_service', sa.String(length=50), nullable=True),
    sa.Column('additional_services', sa.String(length=50), nullable=True),
    sa.Column('discount_offer_used', sa.String(length=10), nullable=True),
    sa.Column('billing_issues_reported', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(length=10), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('report_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('user')
    # ### end Alembic commands ###
